FROM tomcat:11.0-jre17

# Actualizar paquetes e instalar Java
#RUN apt-get update && apt-get upgrade -y && \
#    apt-get install -y openjdk-17-jdk

# Eliminar aplicaciones por defecto
RUN rm -rf /usr/local/tomcat/webapps/*

# Puerto de escucha
EXPOSE 8080

# Comando para arrancar Tomcat
CMD ["catalina.sh", "run"]

#aaaaa
